name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ origin ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Generate manifests
        run: npm run generate-manifests

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '.'
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
